CAMBODIAN_CRISIS = {
    "name": "Cambodian Genocide",
    "start_date": "1975-01-01",
    "end_date": "1978-08-08",
    "location": "Cambodia",
    "kind": "Attack",
    "description": "Long text description of the Cambodian Genocide",
    "human_impact": "Lost 25% of population over three years",
    "economic_impact": "Peasant farming society centralized",
    "maps": ["http://goo.gl/maps/PKI5L"],
    "images": ["http://worldwithoutgenocide.org/wp-content/uploads/2010/01/Cambodia.jpg"],
    "videos": ["http://www.youtube.com/watch?v=1-SI8RF6wDE"],
    "social_media": ["https://twitter.com/UN"],
    "ways_to_help": ["Donation"],
    "resources_needed": ["Monetary donation"],
    "people": [1],
    "organizations": [1],
    "external_links": ["unfoundation.org"],
    "citations": ["http://worldwithoutgenocide.org/genocides-and-conflicts/cambodian-genocide"],
}
AL_GORE = {
    "name": "Al Gore",
    "DOB": "1948-03-31",
    "location": "United States of America",
    "kind": "Vice President",
    "description": "Long text description for Al Gore",
    "maps": ["http://goo.gl/maps/yzrDw"],
    "images": ["http://en.wikipedia.org/wiki/File:Al_Gore_at_SapphireNow_2010_cropped.jpg"],
    "videos": ["http://www.youtube.com/watch?v=-T-yqlH67_4"],
    "social_media": ["https://twitter.com/algore"],
    "crises": [1],
    "organizations": [1],
    "external_links": ["http://www.algore.com/"],
    "citations": ["http://en.wikipedia.org/wiki/Al_Gore"],
}

FEMA = {
    "name": "FEMA",
    "established": "1987-06-19",
    "location": "United States of America",
    "kind": "Disaster Relief",
    "description": "Long text description for FEMA",
    "maps": ["http://goo.gl/maps/yzrDw"],
    "images": ["http://upload.wikimedia.org/wikipedia/commons/3/3a/US-FEMA-Pre2003Seal.svg"],
    "videos": ["http://www.youtube.com/watch?v=UXLXjys9EgM"],
    "social_media": ["https://twitter.com/fema"],
    "crises": [1],
    "people": [1],
    "external_links": ["http://www.fema.gov/"],
    "citations": ["http://en.wikipedia.org/wiki/Federal_Emergency_Management_Agency"],
    "contact_info": {"name": "FEMA",
        "address": "P.O. Box 10055 Hyattsville, MD 20782-8055",
        "email": "None",
        "phone": "800-621-3362"}
}

CRISIS_PUT = {
    "name": "PUTPUTUPDATEUPDATE",
    "start_date": "9999-01-01",
    "end_date": "9999-01-01",
    "location": "CAMBODIA",
    "kind": "ATTACK",
    "description": "LONG TEXT DESCRIPTION SOMETHING SOMETHING",
    "human_impact": "PEOPLE DIED",
    "economic_impact": "SOMETHING ABOUT FARMING",
    "maps": ["http://GOOGLYMAPS"],
    "images": ["http://JPEG.PICTURE"],
    "videos": ["http://VIDEO"],
    "social_media": ["https://TWEETS"],
    "ways_to_help": ["$$$"],
    "resources_needed": ["$$$$$$$$$$"],
    "people": [2],
    "organizations": [2],
    "external_links": ["WIKIPEDIA"],
    "citations": ["BILIOGRAPHY"],
}

ORG_PUT = {
    "name": "FEMA",
    "established": "9999-06-19",
    "location": "USAUSAUSA",
    "kind": "DISASTER RELIEF",
    "description": "FEMA DESCRIPTION",
    "maps": ["http://GOOGLYMAPSFORFEMA"],
    "images": ["http://WIKIPEDIA.DUH"],
    "videos": ["http://GOOGLEPLUSTUBE"],
    "social_media": ["https://FEMATWITTER"],
    "crises": [2],
    "people": [2],
    "external_links": ["http://FEMASWEBSITE"],
    "citations": ["http://BIBLIOGRAPHY.txt"],
    "contact_info": {"name": "FEMA",
        "address": "HYATTSVILLE",
        "email": "FEMA@FEMA.FEMA",
        "phone": "999-999-9999"}
}

PERSON_PUT = {
    "name": "AL GORE",
    "DOB": "9999-03-31",
    "location": "USA!!USA!!USA!!!11!",
    "kind": "NOT THE PRESIDENT",
    "description": "GLOBAL WARMING DUDE",
    "maps": ["http://GOOGLYMAPS"],
    "images": ["http://WIKIPEDIA"],
    "videos": ["http://YOUTUBES"],
    "social_media": ["https://TWITTER"],
    "crises": [2],
    "organizations": [2],
    "external_links": ["http://GLOBALWARMINGISREAL"],
    "citations": ["http://ALGOREWIKI"],
}
